on:
  push:
    branches:
      - main

# Just run a test job that echos
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a test command
        run: echo "This is a test workflow running on push to main branch."